// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onHumidityChange();
void onTemperatureChange();
void onLedStateChange();

float humidity;
float temperature;
bool ledState;

void initProperties(){

  ArduinoCloud.addProperty(humidity, READWRITE, 1 * SECONDS, onHumidityChange);
  ArduinoCloud.addProperty(temperature, READWRITE, 1 * SECONDS, onTemperatureChange);
  ArduinoCloud.addProperty(ledState, READWRITE, ON_CHANGE, onLedStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
